In [336]:
import geopandas
from collections import Counter

In [337]:
openFile = geopandas.read_file("D:/GIS/example_dataset.geojson")
print(openFile.crs)
openFile.head(10)

EPSG:4326

,crop_name,sowing_date,actual_yield,field_id,avg_temperature,avg_rainfall,model_yield,geometry
0,maiz,2016-04-10,7600.0,MS_VN_03_407,11.547103,572.463009,8903.0,"MULTIPOLYGON (((28.16611 49.21513, 28.16624 49..."
1,maiz,2016-04-11,7900.0,MS_VN_03_405,11.547103,574.831401,8814.0,"MULTIPOLYGON (((28.16966 49.19427, 28.16936 49..."
2,maiz,2016-04-12,7900.0,PA_KM_05_1802,12.190627,637.703767,8317.0,"MULTIPOLYGON (((27.30659 48.87534, 27.30674 48..."
3,maiz,2016-04-12,9000.0,MS_VN_03_410,11.756031,588.947718,8878.0,"MULTIPOLYGON (((28.11488 49.21303, 28.11503 49..."
4,maiz,2016-04-12,12100.0,KI_VN_10_0308,11.584644,595.795305,8996.0,"MULTIPOLYGON (((28.86633 49.22147, 28.86651 49..."
5,maiz,2016-04-13,7000.0,PA_KM_05_1803,12.190627,640.868072,8184.0,"MULTIPOLYGON (((27.28864 48.87534, 27.28873 48..."
6,maiz,2016-04-13,6400.0,PA_KM_05_1801,12.190627,640.868072,8184.0,"MULTIPOLYGON (((27.29514 48.87655, 27.29317 48..."
7,maiz,2016-04-13,7300.0,MS_VN_03_409,11.756031,597.970930,8965.0,"MULTIPOLYGON (((28.12418 49.21158, 28.12390 49..."
8,maiz,2016-04-13,11700.0,KI_VN_10_0302,11.584644,598.156220,8875.0,"MULTIPOLYGON (((28.90721 49.23975, 28.90723 49..."
9,maiz,2016-04-14,7100.0,PA_KM_05_1804,12.190627,646.445618,8211.0,"MULTIPOLYGON (((27.28238 48.87403, 27.28251 48..."

In [338]:
print(Counter(openFile['crop_name']), 'Count of cultures ->', len(Counter(openFile['crop_name'])))

Counter({'maiz': 785, 'soy': 209, 'sun': 6}) Count of cultures -> 3

In [339]:
print(openFile.loc[openFile["actual_yield"].idxmax()])
print('--------')
print(openFile.loc[openFile["actual_yield"].idxmin()])

crop_name                                                       maiz
sowing_date                                               2018-04-23
actual_yield                                                 14500.0
field_id                                                MS_VN_03_205
avg_temperature                                            13.204197
avg_rainfall                                              643.851488
model_yield                                                   8096.0
geometry           MULTIPOLYGON (((28.405359888900804 49.06401641...
Name: 450, dtype: object
--------
crop_name                                                        soy
sowing_date                                               2017-04-27
actual_yield                                                   900.0
field_id                                                MS_VN_02_502
avg_temperature                                            11.554349
avg_rainfall                                              625.875383
model_yield                                                   2651.0
geometry           MULTIPOLYGON (((29.071879000003968 48.98033300...
Name: 854, dtype: object